[package]
name = "cargo-qemu-runner"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "A cargo subcommand that allows running Limine kernels using cargo run"
repository = "https://github.com/Qwinci/cargo-qemu-runner"

[dependencies]
cargo_metadata = "0.18.1"
serde_json = "1.0.112"
serde = { version = "1.0.196", features = ["derive"] }
git2 = "0.20.0"
indicatif = "0.17.9"
